'use strict';
(() => {
  const deals=[['CLASSIC<br>SMASH BURGER','FRIES + CAN OF POP','10.99'],['DONAIR<br>SMASH BURGER','FRIES + CAN OF POP','11.99'],['GAME CHANGER<br>BEEF POUTINE','+ CAN OF POP','13.99'],['WESTERN<br>BEEF POUTINE','+ CAN OF POP','13.99'],['SPICY CHICKEN<br>POUTINE','+ CAN OF POP','15.99'],['ALBERTA<br>CLASSIC BEEF','FRIES + CAN OF POP','13.99'],['SWEET &amp; SPICY<br>BEEF','FRIES + CAN OF POP','13.99'],['HONEY GARLIC<br>CHICKEN','FRIES + CAN OF POP','15.99'],['TASTY THAI<br>RICE BOX','BEEF + CAN OF POP','12.99'],['CARIBBEAN<br>RICE BOX','CHICKEN OR MIX + CAN OF POP','14.99']];
  const ENTRANCE_MS=650,STAGGER_MS=1400,HOLD_MS=8000,EXIT_MS=650,EMPTY_MS=1000;
  const section=document.querySelector('.deals'),slots=Array.from({length:5},()=>section.appendChild(Object.assign(document.createElement('div'),{className:'slot'}))),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  function resize(){document.documentElement.style.setProperty('--scale',Math.min(innerWidth/1080,innerHeight/1920));} resize();addEventListener('resize',resize,{passive:true});
  function card(index){const [name,inclusion,price]=deals[index],el=document.createElement('article');el.className='card';el.dataset.deal=String(index+1);el.innerHTML=`<span class="number">${index+1}</span><img class="food" src="deal-${index+1}.png" alt="${name.replace(/<br>/g,' ')} with included drink${inclusion.includes('FRIES')?' and fries':''}" width="320" height="180"><div class="info"><h2 class="name">${name}</h2><p class="inclusion"${index===9?' style="font-size:23px"':''}>${inclusion}</p><p class="price">$${price}</p></div>`;return el;}
  const images=deals.map((_,i)=>{const image=new Image();image.src=`deal-${i+1}.png`;return image;}),pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  async function enter(slot,index){slot.append(card(index));if(slot.animate){const a=slot.animate([{opacity:0,transform:reduced?'none':'translateX(55px)'},{opacity:1,transform:'translateX(0)'}],{duration:ENTRANCE_MS,easing:'cubic-bezier(.22,.7,.25,1)',fill:'both'});await a.finished;a.cancel();}else await pause(ENTRANCE_MS);}
  async function clearGroup(){const a=section.animate?section.animate([{opacity:1},{opacity:0}],{duration:EXIT_MS,easing:'ease-in-out',fill:'both'}):null;if(a)await a.finished;else await pause(EXIT_MS);slots.forEach(slot=>slot.replaceChildren());if(a)a.cancel();}
  async function play(){await Promise.all(images.map(img=>img.decode?img.decode().catch(()=>{}):Promise.resolve()));await pause(EMPTY_MS);let group=0;for(;;){for(let row=0;row<5;row++){if(row)await pause(STAGGER_MS-ENTRANCE_MS);await enter(slots[row],group*5+row);}await pause(HOLD_MS);await clearGroup();await pause(EMPTY_MS);group=1-group;}}
  play();
})();
